### ISSUE TITLE
which is the null hypothesis?

### ISSUE THREAD

**Issue by Angela446-lgtm** [syanga/pycit#1]
pval = itest(df.iloc[:,ix].values,  df.iloc[:,jx].values, test_args={'statistic': 'mixed_mi', 'n_jobs': 8})
is_independent = (pval >= 1.- 0.95) #confidence_level = 0.95

So, the output is True. So, the two variables are independent.

Which is the null hypothesis here?

**Comment by syanga** [comment]
The null hypothesis usually refers to independence
